### ISSUE TITLE
Time zone

### ISSUE THREAD

**Issue by nitishMehrotra** [MOOVE-Network/moove-webapp#20]
> Required for Dry-Runs

**Comment by yurixus** [comment]
This looks like it's fixed judging by our call this morning. @nitishMehrotra please reassign to yourself. Thanks!

**Comment by nitishMehrotra** [comment]
@yurixus Just checked on the test build for driver and employee that you shared and the issue is still there. Still have to go the settings and change the time zone to GMT 00:00 (London)

On backend however the issue is fixed.

**Comment by nitishMehrotra** [comment]
@yurixus On the app issue is fixed the but the issue is still present on the webapp with the date time picker. Please refer to Issue #37 for explanation on the issue.
