### ISSUE TITLE
Can't assign a driver to a manifest

### ISSUE THREAD

**Issue by nitishMehrotra** [MOOVE-Network/moove-webapp#21]
> Required for Dry-Runs

**Invision Link:** https://projects.invisionapp.com/share/YX8CC6CVU#/screens/185371376

**Description:**
When a driver is dispatched with a manifest the driver doesn't receive a push notification and nor there is a screen to look at his upcoming trips.

Steps to reproduce the issue:
1. Log in the web app as an operator (operator@n3wnormal.com/password1)
2. Select Jobs from the NavBar.
3. Click on Unassigned Rosters tab.
4. Select an unassigned roster from the list by selecting the checkbox.
5. Click on dispatch.
6. Create the pool of employees by selecting the checkbox
8. Select a driver which are present on the system.
7. Click on dispatch.
8. The selected driver should receive a push notificaiton and the his upcoming trips should get updated.

Point 8 doesn't happen.

**Comment by yurixus** [comment]
Went through the process with Nitish, all worked fine. Reassigning back.

**Comment by yurixus** [comment]
@nitishMehrotra it looks like I can't reassign it. Can you check permissions for me please?
