### ISSUE TITLE
Time zone issue in Employee Scheduling

### ISSUE THREAD

**Issue by nitishMehrotra** [MOOVE-Network/moove-webapp#37]
**Description:**

The range selector is not working on the local time zone. Please refer to [this](https://drive.google.com/file/d/0B4xxRKgEKT6AZ3dqb1VNclBBNHc/view?usp=sharing) video for steps on reproducing the issue.

The shift was setup at 1600 local time (IST). In the UI we see the local time correctly. However when the range picker is querying from the backend then it is not considering the local time.

In the video you will see that I had to set the ranger picker time to GMT time to get the schedules.

**Comment by yurixus** [comment]
@nitishMehrotra checking on this...

**Comment by yurixus** [comment]
@nitishMehrotra just in case I'll ask.. you did remember to delete employees after Sunday and create all new ones, right?

**Comment by nitishMehrotra** [comment]
Yes

**Comment by yurixus** [comment]
this is fixed on test env
