### ISSUE TITLE
Employee Setup schedule UI inconsistent

### ISSUE THREAD

**Issue by nitishMehrotra** [MOOVE-Network/moove-webapp#7]
> **Required for Dry Runs**

**User Story Ref**: EMR.UC3.US7
**Invision Link:** https://projects.invisionapp.com/share/458CC6GB7#/screens/190650138

**Description:**
In the current system, the setup schedule UI for an employee is inconsistent with the design. 

Steps:
1. Login to the web app with credentials employer@n3wnormal.com/password2
2. Click on Provisioning 
3. Click on Setup schedule of an already provisioned employee or provision an employee.
4. Check the UI of the pop-up dialog
5. There is no way to create a schedule for a particular day/date/week.

**Incorrect UI Screenshot**
<img width="1440" alt="screen shot 2017-01-04 at 6 11 54 pm" src="https://cloud.githubusercontent.com/assets/3133988/21642586/4b786054-d2a9-11e6-9d51-e48e555e98f9.png">

**Resolution:**
Refer to the Invision link provided above for the correct UI.

**Comment by laurablamo** [comment]
assigned to @jasmine in BLAMO Asana project to see if this is allright

**Comment by laurablamo** [comment]
**UX Comments** from @jasmine
I think this is fine if the shift would happen everyday and would not get overnight 
(eg. 22:00 Mon - 6:00 Tue)

Also, I'm not sure if the system should support "create a schedule for a particular day/date/week" if we are only letting Employer to set one week schedule every week.

Suggest we add a delete button?

**Comment by nitishMehrotra** [comment]
In the pilot we will not have overnight shifts.

The employer can setup schedule for an employee for more than a week. That is the capability we get from the experience drawn in the Invision link. With the current implementation after every week the employer needs to go and setup the schedule which is a bad user experience. 

Not sure what how a delete button will help

**Comment by nitishMehrotra** [comment]
Dependent on Issue #36

**Comment by jasminelinblamo** [comment]
We should add "previous week" and "next week" buttons as InVision since there's flexibility to add shift weeks after.

I'm thinking maybe Operator would need the flexibility to delete shift but we can skip this if it's not the case.

**Comment by nitishMehrotra** [comment]
Refer to Issue #36. Since we have cron jobs week UI was not implemented by devs.

Closing this as of now.
